adfddagcffbgcbbaficeaajabgcfeafgfaebfcfcjfjgbfbdecddddjjjcahbbae = 3
babdghbichfhfecaadhfbedcaccgdhfechefieeacaafaefffcebedgcjhafdadb = -6
fbgcbeaibfgjajcfeddbccdddffddjcdgccbiejcffbfebeaefifcahbbehcaedf = babdghbichfhfecaadhfbedcaccgdhfechefieeacaafaefffcebedgcjhafdadb + adfddagcffbgcbbaficeaajabgcfeafgfaebfcfcjfjgbfbdecddddjjjcahbbae
print(adfddagcffbgcbbaficeaajabgcfeafgfaebfcfcjfjgbfbdecddddjjjcahbbae)
print(fbgcbeaibfgjajcfeddbccdddffddjcdgccbiejcffbfebeaefifcahbbehcaedf)