adfddagcffbgcbbaficeaajabgcfeafgfaebfcfcjfjgbfbdecddddjjjcahbbae = 3
babdghbichfhfecaadhfbedcaccgdhfechefieeacaafaefffcebedgcjhafdadb = -6
ecfbdfhaejdehciefbeibfdbjdahbbdfecadahacfigcbidacfhgchedejcejcij = 5
fbgcbeaibfgjajcfeddbccdddffddjcdgccbiejcffbfebeaefifcahbbehcaedf = babdghbichfhfecaadhfbedcaccgdhfechefieeacaafaefffcebedgcjhafdadb + adfddagcffbgcbbaficeaajabgcfeafgfaebfcfcjfjgbfbdecddddjjjcahbbae
fbgcbeaibfgjajcfeddbccdddffddjcdgccbiejcffbfebeaefifcahbbehcaedf = fbgcbeaibfgjajcfeddbccdddffddjcdgccbiejcffbfebeaefifcahbbehcaedf + ecfbdfhaejdehciefbeibfdbjdahbbdfecadahacfigcbidacfhgchedejcejcij
print(fbgcbeaibfgjajcfeddbccdddffddjcdgccbiejcffbfebeaefifcahbbehcaedf)